### hmenu config file.

# Special executable.
executable = "/path/to/other/dmenu/executable/if/not/in/PATH"
# executable = "dmenu-in-path"

# Script with which to open files.
open = "my-open-script"

# Actual files to open.
files =
    # All of these work, any path not starting with '/' or '~' will get $HOME
    # slapped in front of it.
    [ ".config/hmenu/hmenu.toml"
    , "~.config/hmenu/hmenu.toml"
    , "/home/USER/.config/hmenu/hmenu.toml"

    , "~/.scripts/"  # All of the files in the .scripts directory
    ]

# Terminal emulator with which to open tty programs.
# Defaults to "xterm"
terminal = "st"

# Programs one would like to open in a terminal when calling them from dmenu.
tty-programs =
    [ "neomutt"
    ]
