### hmenu config file.

# Special executable.
executable = "/path/to/other/dmenu/executable/if/not/in/PATH"
# executable = "dmenu-in-path"

# Script with which to open files.
open = "my-open-script"

# Prefix that will appear in front of the files in dmenu.
file-prefix = "f:"

# Actual files to open.
files =
    # Path is relative to $HOME
    [ ".config/hmenu.toml"
    ]
