### hmenu config file.

# Special executable.
executable = "/path/to/other/dmenu/executable/if/not/in/PATH"
# executable = "dmenu-in-path"

# Script with which to open files.
open = "my-open-script"

# Actual files to open.
files =
    # All of these work, any path not starting with '/' or '~' will get $HOME
    # slapped in front of it.
    [ ".config/hmenu/hmenu.toml"
    , "~.config/hmenu/hmenu.toml"
    , "/home/USER/.config/hmenu/hmenu.toml"
    ]
