name:                hmenu
version:             0.2.2
synopsis:            A small wrapper around dmenu
license:             GPL-3
author:              Slot
maintainer:          soliditsallgood@tuta.io
homepage:            https://gitlab.com/slotThe/hmenu
tested-with:         GHC == 8.6.5

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - FlexibleContexts

ghc-options:
  -O2
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints

dependencies:
  - base
  - directory
  - text
  - process
  - process-extras
  - containers
  - tomland
  - filepath
  - posix-paths
  - bytestring
  - attoparsec

executables:
  hmenu:
    source-dirs: src
    main: hmenu.hs
