name:                hmenu
version:             0.2.3
synopsis:            A small wrapper around dmenu
license:             GPL-3
author:              Slot
maintainer:          soliditsallgood@tuta.io
homepage:            https://gitlab.com/slotThe/hmenu
tested-with:         GHC == 8.10.4

default-extensions:
  - StrictData
  - OverloadedStrings
  - NamedFieldPuns
  - FlexibleContexts
  - MultiWayIf
  - BlockArguments
  - ScopedTypeVariables
  - LambdaCase

ghc-options:
  -O2
  -Wall
  -Wcompat
  -Widentities
  -Wmissing-export-lists
  -Wredundant-constraints
  -Wmissed-specialisations
  -Wincomplete-uni-patterns
  -Wmissing-local-signatures
  -Wincomplete-record-updates

dependencies:
  - name: base
    mixin: hiding (Prelude)
  - base-prelude
  - containers
  - text
  - bytestring           <  0.11
  - bytestring-lexing
  - double-conversion
  - posix-paths
  - directory
  - unix
  - process
  - process-extras
  - tomland              >= 1.3.0.0
  - optparse-applicative

library:
  source-dirs: src/

executables:
  hmenu:
    source-dirs: app
    main: Main.hs
    dependencies: hmenu

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hmenu
      - hspec
      - QuickCheck
