name:                hmenu
version:             0.2.4
synopsis:            A small wrapper around dmenu
license:             GPL-3
author:              Slot
maintainer:          soliditsallgood@mailbox.org
homepage:            https://gitlab.com/slotThe/hmenu
tested-with:         GHC == 9.2.5

ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-unsafe
  -Wno-all-missed-specialisations
  -O2

language: GHC2021

default-extensions:
  - BlockArguments
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - StrictData

dependencies:
  - name: base
  - base-prelude
  - containers
  - text
  - bytestring
  - bytestring-lexing
  - utf8-string
  - double-conversion
  - posix-paths
  - directory
  - unix
  - process
  - process-extras
  - tomland              >= 1.3.0.0
  - optparse-applicative

library:
  source-dirs: src/

executables:
  hmenu:
    source-dirs: app
    main: Main.hs
    dependencies: hmenu

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hmenu
      - hspec
      - QuickCheck
