name:                hmenu
version:             0.1.1
synopsis:            A small wrapper around dmenu
license:             GPL-3
author:              Slot
maintainer:          soliditsallgood@tuta.io
homepage:            to-come
tested-with:         GHC == 8.6.5

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - MultiWayIf
  - FlexibleContexts

ghc-options:
  -O2
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints

dependencies:
  - base
  - mtl
  - directory
  - text
  - process
  - containers
  - tomland
  - filepath

executables:
  hmenu:
    source-dirs: src
    main: hmenu.hs
