name:                hdmenu
version:             0.3.0
synopsis:            A small wrapper around dmenu
license:             GPL-3
author:              Tony Zorman
maintainer:          Tony Zorman <soliditsallgood@mailbox.org>
github:              slotThe/hmenu
category:            system
tested-with:         GHC == 9.8.4
description:         hdmenu is a small wrapper around dmenu that can
                       1. Display commands in order of usage and,
                          optionally, apply a frequency decay
                          every time an item is selected.
                       2. Specify extra files to consider, which
                          will be opened by a program of your
                          choice (e.g., xdg-open).
                       3. Open certain executables inside of your
                          terminal.

extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-unsafe
  -Wno-all-missed-specialisations
  -O2

language: GHC2021

default-extensions:
  - BlockArguments
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - StrictData

dependencies:
  - base                 >= 4.17.2 && < 4.22
  - base-prelude         >= 1.6.1  && < 1.7
  - bytestring           >= 0.11.5 && < 0.13
  - bytestring-lexing    >= 0.5.0  && < 0.6
  - containers           >= 0.6.7  && < 0.8
  - directory            >= 1.3.7  && < 1.5
  - unix                 >= 2.7.3  && < 3
  - double-conversion    >= 2.0.4  && < 2.1
  - text                 >= 2.0.2  && < 2.2
  - optparse-applicative >= 0.17.1 && < 0.19
  - process              >= 1.6.18 && < 1.7
  - posix-paths          >= 0.3.0  && < 0.4
  - process-extras       >= 0.7.4  && < 0.8
  - utf8-string          >= 1.0.2  && < 1.1
  - tomland              >= 1.3.3  && < 1.4

library:
  source-dirs: src/

executables:
  hdmenu:
    source-dirs: app
    main: Main.hs
    dependencies: hdmenu

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hdmenu
      - hspec
      - QuickCheck
