name:                hmenu
version:             0.2.3
synopsis:            A small wrapper around dmenu
license:             GPL-3
author:              Slot
maintainer:          soliditsallgood@tuta.io
homepage:            https://gitlab.com/slotThe/hmenu
tested-with:         GHC == 8.6.5

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - FlexibleContexts

ghc-options:
  -O2
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints

dependencies:
  - base
  - directory
  - text
  - process
  - process-extras
  - containers
  - tomland
  - posix-paths
  - bytestring
  - attoparsec
  - unix
library:
  source-dirs: src/

executables:
  hmenu:
    source-dirs: app
    main: hmenu.hs
    dependencies: hmenu

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - hspec-attoparsec
      - QuickCheck
